name: PR
permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Cargo Build Minimal Example
        run: cargo build --example minimal

      - name: Cargo Build Krypta Example
        run: cargo build --example krypta

      - name: Cargo Build Movement Example
        run: cargo build --example movement

      - name: Cargo Build Tiled Krypta Example
        run: cargo build --example tiled_krypta

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: true
